baseurl = "/"
languageCode = "en-us"
title = "Mahmood Hasan"
theme = "hugo-lithium"
googleAnalytics = "UA-157708919-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight= 1

[[menu.main]]
    name = "Softwares"
    url = "/softwares/"
    weight= 3

[[menu.main]]
    name = "Presentation"
    url = "/presentation/"
    weight= 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

