---
title: Knowledge Mobilization
author: Mahmood Hasan
date: '2021-01-27'
slug: knowledge-mobilization
categories: []
tags: [K* Continuum, Knowledge Mobilization]
---

1) Specific question I would like to know what you level of familiarity is with visual design/information design and design software namely data visualization or data storytelling)? Be specific, and if you have examples even better.

Answer:
The use of Data visualization to better represent data or a concept has been a crucial component of my academic life. I have written several research papers during my undergraduate and graduate studies. I used software, such as STATA (for continuous and discrete data), GRETL and EViews (for time series data) and Excel. Moreover, I took a course in software R which focused primarily on data visualizations. In R, I have expertise in using packages such as “ggplot”, “plotly”, “gganimate”, “gifski” and “googleVis” to name a few.

 Additionally, I am proficient in using Tableau to do visual design/information design. Specifically, I can collect data from various sources, clean data and make interactive dashboards. Among other charts and plots, I have also prepared interactive dashboards using Slicer in Microsoft Excel.
Please visit www.mahmoodh.com  for specific data visualization examples.


2) Specific question, I would like to know if we would be able to keep your CV on file, there is significant interest in hiring people with skillsets and backgrounds that are different from where we traditionally recruit, and this will not be the last call for job openings within the Research Innovation Lab Directorate.

Answer:
Yes.

3) More general question I have included two diagrams that present a modelling of the knowledge mobilization continuum (this is just one of many examples of knowledge mobilization or knowledge translation). I am curious based on your experience, your strengths/weaknesses, or your interests (where you would like to improve), where you see yourself within these diagrams?



Answer:
The activities of collaboration and dialogue under the Co-Creation domain has been an integral part of my academic and work career. For example, while working on my thesis- ‘Demand Modelling of Solar Photovoltaic: Evidence from Nova Scotia’- due to lack of available data on the Solar industry, I had to communicate with several industry stakeholders and local government authorities to collect information and data. Moreover, the intensity and importance of my work required weekly meetings with my thesis committee. Co-Creation played a major role in creating the final product. 


 I currently work as an Analyst at Cowan Insurance Group where I use software such as R, Excel, and Power BI to analyze data and perform several of the activities as mentioned under the Broker domain and some activities from the Co-Creation domain. I work with individual-level health insurance claims data which allows me to study health claims patterns. I link previous periods data, collaborate with insurance providers, colleagues, and clients to prepare reports to inform the clients about: claims projections, gaps in the plans and offer alternative plan design.  

  I have also performed several activities under the Exchange domain. While at work I have attended several workshops offered by different organizations to learn about the industry and the drug market. Additionally, I was a teaching assistant of 7 courses during my graduate studies at Dalhousie and this enabled me to teach and engage with students from various backgrounds and provide mentorships. 

  Finally, the data visualizations in my website are a good representation of the importance of websites, blogs, and research papers for knowledge dissemination. I have attended a conference where I presented my thesis findings and was part of the organizing team in two conferences. Through attending conferences, I have learned about key and pressing issues that challenge us today. I have also appeared on television as an actor in a TV series!

 Overall, my expertise matches closely with the Knowledge translator functions under the K* Continuum. As per my understanding, the different domains of Knowledge Mobilizations are not mutually exclusive and K* practitioners are likely to undertake several activities from each domain at the same time; but the combination of different activities will vary depending on circumstances. I find myself in a similar situation. This also means that I am not able to focus on a specific domain of Knowledge Continuum and specialization is certainly important.However, I have a lot of enthusiasm and passion to explore the world of using data analytics (including data visualizations) to enhance and aid knowledge sharing which is indeed crucial in transferring the right and impactful kind of knowledge across stakeholders.
  

